# https://github.com/jimschubert/labeler-action
# Enable labeler on issues and pull requests

enable:
  issues: true
  prs: true

# Automatically send a message into the issue/pull request

comments:
  issues: |
    Thanks for opening this issue!
    I may have applied some labels to make clear what your issue is about.

    Please review the labels and make any necessary changes.
  prs: |
    Thanks for the contribution!
    I may have applied some labels to make clear what your pull request is about.

    Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  'bug':
    include:
      - '(B|b)ug([^a-zA-Z0-9]|s)'
    exclude: []
  'help wanted':
    include:
      - '\bhelp( me)?\b'
    exclude:
      - '\b\[test(ing)?\]\b'
  'enhancement':
    include:
      - '(F|f)eature'
      - '(I|i)mprove'
      - '(E|e)nhance'
    exclude: []
