# https://github.com/srggrs/assign-one-project-github-action
# https://github.com/jimschubert/labeler-action
name: Community Actions

on:
  issues:
    types: [opened, edited, milestoned]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign-project:
    runs-on: ubuntu-latest

    steps:
      - name: 🤖 Assign to project
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/niklas2810/maven-template/projects/1'
      #- name: 🏷️ Add Labels
      #  uses: jimschubert/labeler-action@v1
      #  with:
      #    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}